# -*- coding: utf-8 -*-
"""Capinpin_Stéphane_2_clustering_visualisations_102025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NWA7C8IXKysOMlLtxt-uHAxBU1jbPker

# ACP
"""

# -*- coding: utf-8 -*-
# Inspecteur complet de colonnes pour "Bilans_Chicken_2000-2018.csv"

import pandas as pd
import numpy as np
from pathlib import Path

# --------- Paramètres ----------
FICHIER = "Bilans_Chicken_2000-2018.csv"  # adapter le chemin si besoin
MAX_AFFICHAGE_VALEURS = 50                # si une colonne a <= ce nombre de valeurs uniques, on les affiche toutes
Apercu_N = 5                              # nb de lignes à afficher pour l'aperçu
# --------------------------------

def charger_csv(path):
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Fichier introuvable: {path.resolve()}")
    # 1) essai UTF-8 (avec BOM) + auto-détection séparateur
    try:
        df = pd.read_csv(path, sep=None, engine="python", encoding="utf-8-sig")
        return df
    except UnicodeDecodeError:
        # 2) fallback Latin-1 (très courant pour fichiers FR)
        df = pd.read_csv(path, sep=None, engine="python", encoding="latin-1")
        return df

def essayer_dates(serie):
    """Tente de convertir en datetime pour repérer d'éventuelles colonnes de dates."""
    # On évite les séries très longues de texte en limitant le coût
    s = pd.to_datetime(serie, errors="coerce", dayfirst=True, infer_datetime_format=True)
    # Si au moins 70% sont des dates valides, on considère que c'est une date
    valid_ratio = s.notna().mean()
    return s if valid_ratio >= 0.7 else None

df = charger_csv(FICHIER)

print("=== Infos générales ===")
print(f"Fichier           : {FICHIER}")
print(f"Dimensions        : {df.shape[0]:,} lignes x {df.shape[1]:,} colonnes".replace(",", " "))
print("Colonnes          :", list(df.columns))
print("\n--- Aperçu (head) ---")
display(df.head(Apercu_N))
print("\n--- Aperçu (tail) ---")
display(df.tail(Apercu_N))
print("\n--- dtypes / mémoire ---")
print(df.info())

# Détection éventuelle d'une colonne 'index' à utiliser comme index
if "index" in df.columns and df["index"].is_monotonic_increasing:
    try:
        df = df.set_index("index", drop=True)
        print("\n[INFO] Colonne 'index' utilisée comme index de DataFrame.")
    except Exception:
        pass

print("\n\n================= DÉTAIL PAR COLONNE =================")
for i, col in enumerate(df.columns, start=1):
    s = df[col]
    n = len(s)
    nb_na = s.isna().sum()
    nuniq = s.nunique(dropna=True)

    print("\n" + "="*80)
    print(f"[{i}/{len(df.columns)}] Colonne : {col!r}")
    print("-"*80)
    print(f"Type pandas      : {s.dtype}")
    print(f"Lignes           : {n:,}".replace(",", " "))
    print(f"Valeurs uniques  : {nuniq:,}".replace(",", " "))
    print(f"Valeurs manquantes (NaN) : {nb_na:,}".replace(",", " "))

    # Tentative d'interprétation date si object
    parsed_dates = None
    if s.dtype == "object":
        parsed_dates = essayer_dates(s)

    # Affichage spécifique selon type/usage
    if pd.api.types.is_numeric_dtype(s):
        desc = s.describe(percentiles=[0.05, 0.5, 0.95])
        print("\n— Statistiques numériques —")
        print(desc.to_string())
        # Top 20 modalités (utile même pour numériques discrets)
        vc = s.value_counts(dropna=False).head(20)
        print("\nTop 20 fréquences :")
        print(vc.to_string())
    elif parsed_dates is not None:
        # Colonne interprétable comme dates
        print("\n— Colonne détectée comme DATE —")
        print(f"Plage : {parsed_dates.min()}  →  {parsed_dates.max()}")
        # Exemple de fréquences par année/mois si pertinent
        try:
            print("\nRépartition par année (top 20) :")
            print(parsed_dates.dt.year.value_counts(dropna=True).sort_index().tail(20).to_string())
        except Exception:
            pass
    else:
        # Catégoriel/texte
        vc = s.value_counts(dropna=False)
        if nuniq <= MAX_AFFICHAGE_VALEURS:
            print(f"\n— Toutes les valeurs distinctes (<= {MAX_AFFICHAGE_VALEURS}) —")
            # Affiche avec les effectifs pour être utile
            print(vc.to_string())
        else:
            print("\n— Extrait des valeurs (top 20) —")
            print(vc.head(20).to_string())
            # Exemple d'échantillon aléatoire de valeurs distinctes
            try:
                ech = pd.Series(s.dropna().unique())
                if len(ech) > 0:
                    sample = ech.sample(min(20, len(ech)), random_state=42).tolist()
                    print("\nÉchantillon de valeurs distinctes :", sample)
            except Exception:
                pass

print("\n\n>>> Inspection terminée.")

# =========================
# ACP "où s'implanter" - Poulet/Volaille
# Filtre pays à partir de "donneesmondiales.com"
# + EXCLUSION "Chine, continentale"
# + Cercle des corrélations (PC1–PC2)
# + Colonnes utilisées
# + Tableaux Top 5 variables pour PC1 et PC2 (|loadings|)
# =========================

# from google.colab import files
# uploaded = files.upload()  # Choisir Bilans_Chicken_2000-2018.csv si besoin
# path = list(uploaded.keys())[0]
path = "Bilans_Chicken_2000-2018.csv"  # <-- adapte si besoin

# ----- PARAMÈTRE DE SÉLECTION -----
# "countries_from_dm" : garde uniquement les PAYS apparaissant dans 'donneesmondiales.com',
#                       puis utilise toutes les données du fichier pour ces pays (années <= 2018).
# "rows_only_dm"      : n'utilise QUE les LIGNES dont Code Domaine == 'donneesmondiales.com'.
MODE = "countries_from_dm"  # ou "rows_only_dm"

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import re

# 1) Chargement (colonnes utiles)
usecols = ["Zone", "Année", "Produit", "Élément", "Valeur", "Code Domaine"]
dtypes = {
    "Zone": "string",
    "Année": "int32",
    "Produit": "string",
    "Élément": "string",
    "Valeur": "float32",
    "Code Domaine": "string",
}
df = pd.read_csv(path, usecols=usecols, dtype=dtypes, low_memory=True)

# 2) Restreindre sur "donneesmondiales.com"
if MODE == "countries_from_dm":
    dm_countries = (
        df.loc[df["Code Domaine"] == "donneesmondiales.com", "Zone"]
        .dropna().unique().tolist()
    )
    print(f"Pays détectés dans 'donneesmondiales.com' : {len(dm_countries)}")
    df = df[df["Zone"].isin(dm_countries)].copy()
    df = df[df["Année"] <= 2018].copy()
elif MODE == "rows_only_dm":
    df = df[df["Code Domaine"] == "donneesmondiales.com"].copy()
else:
    raise ValueError("MODE doit être 'countries_from_dm' ou 'rows_only_dm'.")

# >>> EXCLUSION demandée : "Chine, continentale"
mask_rm = df["Zone"].astype(str).str.strip().str.casefold().eq("chine, continentale")
# mask_rm = df["Zone"].astype(str).str.strip().str.casefold().isin(["chine, continentale", "chine"])
n_removed = int(mask_rm.sum())
df = df[~mask_rm].copy()
print(f"[Info] 'Chine, continentale' retirée du dataset : {n_removed} ligne(s) supprimée(s).")

# 3) Normalisation texte + filtre produits poulet/volaille/œufs
df["produit_norm"] = df["Produit"].str.casefold()
df["element_norm"] = df["Élément"].str.casefold()

mots_cles_poulet = [
    "poulet", "poulets",
    "volaille", "volailles",
    "poultry",
    "oeuf", "œuf", "oeufs", "œufs",
]
pattern = "|".join(re.escape(k) for k in mots_cles_poulet)
mask_chicken = df["produit_norm"].str.contains(pattern, na=False, regex=True, flags=re.IGNORECASE)
df_ch = df[mask_chicken].copy()

# 4) Sélection d'indicateurs (Élément)
elements_gardes = {
    "production",
    "importations - quantité",
    "exportations - quantité",
    "nourriture",
    "aliments pour animaux",
    "autres utilisations (non alimentaire)",
    "pertes",
    "traitement",
    "résidus",
    "variation de stock",
    "disponibilité alimentaire (kcal/personne/jour)",
    "disponibilité alimentaire en quantité (kg/personne/an)",
}
df_ch = df_ch[df_ch["element_norm"].isin(elements_gardes)].copy()

if df_ch.empty:
    raise ValueError(
        "Aucune donnée après filtrage (produits/éléments). "
        "Essaie MODE='countries_from_dm' ou élargis le filtre produits/éléments."
    )

# 5) Pivot pays-année x Élément
pivot = (
    df_ch.pivot_table(
        index=["Zone", "Année"],
        columns="element_norm",
        values="Valeur",
        aggfunc="sum",
        observed=True,
    )
    .reset_index()
)

# 6) Choix du dernier millésime par pays
pivot = pivot.sort_values(["Zone", "Année"])
pivot_last = pivot.drop_duplicates(subset="Zone", keep="last").reset_index(drop=True)

# 7) Préparation features
idx = pivot_last[["Zone", "Année"]].copy()
X = pivot_last.drop(columns=["Zone", "Année"])
colonnes_features = X.columns.tolist()

# 7bis) Imputation médiane + retrait variance nulle
imputer = SimpleImputer(strategy="median")
X_imp = imputer.fit_transform(X)
variances = np.var(X_imp, axis=0)
keep_mask = variances > 0
if keep_mask.sum() < 2:
    raise ValueError("Trop peu de variables avec variance non nulle pour l'ACP.")
X_imp = X_imp[:, keep_mask]
colonnes_features = [c for c, k in zip(colonnes_features, keep_mask) if k]

# 8) Standardisation
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_imp)

# 9) ACP
n_components = min(5, X_scaled.shape[1])
pca = PCA(n_components=n_components, random_state=42)
X_pca = pca.fit_transform(X_scaled)
explained = pca.explained_variance_ratio_
eigenvalues = pca.explained_variance_

# 10) Scores & export
res = pd.DataFrame({"Zone": idx["Zone"], "Année": idx["Année"]})
for i in range(n_components):
    res[f"PC{i+1}"] = X_pca[:, i]
res.to_csv("ACP_scores_pays_chicken_filtre_dm.csv", index=False)
print("Scores ACP exportés -> ACP_scores_pays_chicken_filtre_dm.csv")

# 11) Colonnes utilisées (libellés d'origine si possible)
map_elem = (
    df_ch[["Élément", "element_norm"]].drop_duplicates()
    .set_index("element_norm")["Élément"].to_dict()
)
colonnes_pretty = [map_elem.get(c, c) for c in colonnes_features]
print("\nColonnes utilisées pour l'ACP :")
for c in colonnes_pretty:
    print(" -", c)

# 12) Loadings (contributions des variables aux composantes)
loadings = pd.DataFrame(
    pca.components_.T,                     # (variables x composantes)
    index=colonnes_pretty,
    columns=[f"PC{i+1}" for i in range(n_components)]
)

# 12bis) Petits tableaux Top 5 variables sur PC1 et PC2 (par |loading|)
def top_k_table(load_df, pc, k=5):
    k = min(k, load_df.shape[0])
    abs_vals = load_df[pc].abs()
    order = abs_vals.sort_values(ascending=False).head(k).index
    out = pd.DataFrame({
        "Variable": order,
        f"|loading {pc}|": abs_vals.loc[order].values,
        f"loading {pc} (signé)": load_df.loc[order, pc].values,
    })
    return out

top5_pc1 = top_k_table(loadings, "PC1", k=5)
top5_pc2 = top_k_table(loadings, "PC2", k=5)

print("\nTop 5 variables (par |loading|) sur PC1 :")
print(top5_pc1.to_string(index=False))
print("\nTop 5 variables (par |loading|) sur PC2 :")
print(top5_pc2.to_string(index=False))

# 13) Graphiques (matplotlib seul, 1 figure = 1 plot)
# 13a) Scree plot (variance expliquée cumulée)
plt.figure()
plt.plot(range(1, n_components+1), np.cumsum(explained), marker="o")
plt.xlabel("Nombre de composantes")
plt.ylabel("Variance expliquée cumulée")
plt.title("Scree plot (ACP poulet/volaille — pays 'donneesmondiales.com')")
plt.grid(True)
plt.show()

# 13b) Nuage des pays PC1 vs PC2 (+ labels pour points extrêmes)
plt.figure()
plt.scatter(res["PC1"], res["PC2"])
plt.xlabel(f"PC1 ({explained[0]*100:.1f}% var.)")
plt.ylabel(f"PC2 ({explained[1]*100:.1f}% var.)")
plt.title("ACP - Pays (filtre 'donneesmondiales.com')")
plt.grid(True)
res["_abs12"] = res["PC1"].abs() + res["PC2"].abs()
for _, row in res.nlargest(20, "_abs12").iterrows():
    plt.annotate(row["Zone"], (row["PC1"], row["PC2"]), fontsize=8)
plt.show()

# 13c) Cercle des corrélations (PC1–PC2)
# Corr(var, PCk) ≈ components_[k, j] * sqrt(explained_variance_[k]) pour données standardisées
components = pca.components_
coords = components[:2, :].T * np.sqrt(eigenvalues[:2])  # (n_features, 2)
x, y = coords[:, 0], coords[:, 1]

theta = np.linspace(0, 2*np.pi, 400)
plt.figure()
plt.plot(np.cos(theta), np.sin(theta))  # cercle unité
plt.axhline(0, linewidth=0.5)
plt.axvline(0, linewidth=0.5)
plt.scatter(x, y)
for i, name in enumerate(colonnes_pretty):
    plt.arrow(0, 0, x[i], y[i], head_width=0.02, length_includes_head=True)
    plt.text(x[i]*1.07, y[i]*1.07, name, fontsize=8)
plt.gca().set_aspect('equal', adjustable='box')
plt.xlim(-1.1, 1.1); plt.ylim(-1.1, 1.1)
plt.title(f"Cercle des corrélations (PC1–PC2)\nPC1: {explained[0]*100:.1f}%  |  PC2: {explained[1]*100:.1f}%")
plt.xlabel("Corrélation avec PC1"); plt.ylabel("Corrélation avec PC2")
plt.grid(True, linestyle="--", linewidth=0.5)
plt.show()

"""PC1 ~ “taille/dynamique de marché” (Nourriture, Production, Pertes,  Importations ; Résidus en sens opposé).
➜ Pays hauts sur PC1 = marchés volumineux/actifs.

PC2 ~ “intensité par habitant” (très porté par kg/personne/an et kcal/personne/jour).
➜ Pays hauts sur PC2 = consommation par tête élevée (pouvoir d’achat/propension).




Cibles “prioritaires” : pays en haut à droite (PC1 et PC2 > médiane).
→ Grands marchés et intensité par habitant élevée.

Niches premium : PC1 faible, PC2 fort.
→ Petits marchés mais clientèle à forte valeur (produits premium).

Mass market prix/volume : PC1 fort, PC2 faible.
→ Gros volumes, intensité moyenne → jouer le prix/volume, formats économiques.

À éviter / à surveiller : PC1 faible, PC2 faible.
→ Marchés petits et peu intenses.
"""

# 14) Cercles des corrélations (PC1–PC2) PAR RÉGION
#     -> Ne conserve que les pays dont le Code Élément (ou Code Domaine) == 'donneesmondiales.com'
#     -> Le titre du graphe est coloré selon la région

# --- Détection de la colonne de code source (préférence: 'Code Élément', fallback: 'Code Domaine')
dm_col_try = ["Code Élément", "Code Domaine"]
dm_col = None
for c in dm_col_try:
    try:
        _tmp = pd.read_csv(path, usecols=["Zone", c], nrows=0)
        dm_col = c
        break
    except Exception:
        continue
if dm_col is None:
    raise ValueError("Aucune colonne 'Code Élément' ou 'Code Domaine' trouvée dans le CSV.")

# --- Pays autorisés: ceux qui ont 'donneesmondiales.com' dans la colonne dm_col
dm_df = pd.read_csv(
    path,
    usecols=["Zone", dm_col],
    dtype={"Zone": "string", dm_col: "string"},
    low_memory=True,
)
allowed_zones = (
    dm_df.loc[dm_df[dm_col].astype("string").str.strip().str.casefold() == "donneesmondiales.com", "Zone"]
    .dropna().unique().tolist()
)
print(f"[Info] Pays avec {dm_col} == 'donneesmondiales.com' : {len(allowed_zones)}")

# --- Mapping Zone -> Region
try:
    reg_df = pd.read_csv(
        path,
        usecols=["Zone", "Region"],
        dtype={"Zone": "string", "Region": "string"},
        low_memory=True,
    )
except ValueError:
    raise ValueError("La colonne 'Region' est introuvable dans le fichier CSV.")
reg_df = reg_df.dropna(subset=["Zone"]).drop_duplicates(subset=["Zone"])
zone_to_region = reg_df.set_index("Zone")["Region"].to_dict()

# --- Base par pays (pivot_last) + filtre sur allowed_zones
df_reg = pivot_last[["Zone", "Année"] + colonnes_features].copy()
df_reg = df_reg[df_reg["Zone"].isin(allowed_zones)].copy()
if df_reg.empty:
    raise ValueError("Aucun pays restant après filtre 'donneesmondiales.com' pour tracer par région.")

# --- Ajout de la région + nettoyage
df_reg["Region"] = df_reg["Zone"].map(zone_to_region)
missing_regions = int(df_reg["Region"].isna().sum())
if missing_regions > 0:
    print(f"[Info] {missing_regions} pays sans 'Region' — ignorés pour les tracés par région.")
df_reg = df_reg.dropna(subset=["Region"]).copy()

regions = sorted(df_reg["Region"].dropna().unique().tolist())
print(f"[Info] Régions détectées (après filtre {dm_col}): {len(regions)} -> {regions}")

# --- Palette de couleurs par région (tab10)
region_colors = {r: plt.get_cmap("tab10")(i % 10) for i, r in enumerate(regions)}

# --- Helper: tracé d'un cercle des corrélations (PC1–PC2)
def plot_correlation_circle(coords, labels, explained_ratio, title_suffix="", title_color=None):
    x, y = coords[:, 0], coords[:, 1]
    theta = np.linspace(0, 2*np.pi, 400)
    plt.figure()
    plt.plot(np.cos(theta), np.sin(theta))  # cercle unité
    plt.axhline(0, linewidth=0.5)
    plt.axvline(0, linewidth=0.5)
    plt.scatter(x, y)
    for i, name in enumerate(labels):
        plt.arrow(0, 0, x[i], y[i], head_width=0.02, length_includes_head=True)
        plt.text(x[i]*1.07, y[i]*1.07, name, fontsize=8)
    plt.gca().set_aspect('equal', adjustable='box')
    plt.xlim(-1.1, 1.1); plt.ylim(-1.1, 1.1)
    plt.title(
        f"Cercle des corrélations (PC1–PC2){title_suffix}\n"
        f"PC1: {explained_ratio[0]*100:.1f}%  |  PC2: {explained_ratio[1]*100:.1f}%",
        color=title_color
    )
    plt.xlabel("Corrélation avec PC1"); plt.ylabel("Corrélation avec PC2")
    plt.grid(True, linestyle="--", linewidth=0.5)
    plt.show()

# --- Boucle régions: ACP dédiée + cercle des corrélations
for reg in regions:
    sub = df_reg[df_reg["Region"] == reg].copy()
    n_countries = sub.shape[0]

    # Données (mêmes features que l'ACP globale, même ordre)
    Xr = sub[colonnes_features].to_numpy()

    # Imputation médiane + retrait variables à variance nulle dans la région
    imp_r = SimpleImputer(strategy="median")
    Xr_imp = imp_r.fit_transform(Xr)
    var_r = np.var(Xr_imp, axis=0)
    mask_r = var_r > 0
    if mask_r.sum() < 2 or n_countries < 2:
        print(f"[Alerte] Région '{reg}': échantillon insuffisant "
              f"(pays={n_countries}, variables actives={int(mask_r.sum())}). Cercle ignoré.")
        continue

    feat_names_r = [c for c, k in zip(colonnes_pretty, mask_r) if k]
    Xr_imp = Xr_imp[:, mask_r]

    # Standardisation + ACP(2)
    scaler_r = StandardScaler()
    Xr_scaled = scaler_r.fit_transform(Xr_imp)
    pca_r = PCA(n_components=2, random_state=42)
    Xr_pca = pca_r.fit_transform(Xr_scaled)  # on n'utilise pas Xr_pca ensuite

    # Coordonnées du cercle des corrélations (PC1–PC2)
    comps_r = pca_r.components_             # (2 x n_features_r)
    eig_r = pca_r.explained_variance_       # (2,)
    coords_r = comps_r[:2, :].T * np.sqrt(eig_r[:2])

    plot_correlation_circle(
        coords_r,
        feat_names_r,
        pca_r.explained_variance_ratio_,
        title_suffix=f" — Région: {reg} (n={n_countries}; filtre {dm_col})",
        title_color=region_colors.get(reg)
    )

# =====================================================================
# POST-ACP : Ranking pays "où se positionner" vs "où éviter"
# (version avec exclusion de "Chine, continentale")
# =====================================================================

import numpy as np
import pandas as pd

# 1) Fusionner scores PC1/PC2 avec les indicateurs pays
F = pivot_last.merge(res[["Zone", "PC1", "PC2"]], on="Zone", how="left").copy()

# >>> EXCLUSION demandée : "Chine, continentale"
# mask_rm = F["Zone"].astype(str).str.strip().str.casefold().eq("chine, continentale")
mask_rm = F["Zone"].astype(str).str.strip().str.casefold().isin(["chine, continentale", "chine"])
n_removed = int(mask_rm.sum())
F = F[~mask_rm].copy()
print(f"[Info] 'Chine, continentale' retirée : {n_removed} ligne(s) supprimée(s).")

# (Optionnel) Pour retirer aussi "Chine", décommente :
# mask_rm2 = F["Zone"].astype(str).str.strip().str.casefold().eq("chine")
# F = F[~mask_rm2].copy()
# print(f"[Info] 'Chine' retirée : {int(mask_rm2.sum())} ligne(s) supprimée(s).")

# 2) Helpers pour récupérer des colonnes même si absentes (remplacées par 0)
def col(df, name):
    return df[name] if name in df.columns else 0.0

# Colonnes utiles (en minuscules, comme dans element_norm)
F["imports"]      = col(F, "importations - quantité").fillna(0)
F["exports"]      = col(F, "exportations - quantité").fillna(0)
F["production"]   = col(F, "production").fillna(0)
F["pertes"]       = col(F, "pertes").fillna(0)
F["kg_per_cap"]   = col(F, "disponibilité alimentaire en quantité (kg/personne/an)").fillna(0)
F["kcal_per_cap"] = col(F, "disponibilité alimentaire (kcal/personne/jour)").fillna(0)

# 3) Indicateurs dérivés (robustes aux zéros)
base_supply = F["production"] + F["imports"]
base_supply_safe = base_supply.replace(0, np.nan)
F["import_reliance"] = (F["imports"] / base_supply_safe).fillna(0)   # 0..1 (plus proche de 1 => + dépendant des importations)
F["waste_rate"]      = (F["pertes"] / base_supply_safe).fillna(0)   # optionnel : inefficiences de chaîne

# 4) Score d’attractivité (pondération simple et transparente)
#    - PC1 (volume) pèse le plus
#    - PC2 (intensité par habitant) en 2e
#    - import_reliance (ouverture aux importations) en 3e
for c in ["PC1", "PC2", "import_reliance"]:
    mu, sd = F[c].mean(), F[c].std(ddof=0)
    F[f"z_{c}"] = 0 if sd == 0 else (F[c] - mu) / sd

F["Attractivite"] = 0.5*F["z_PC1"] + 0.35*F["z_PC2"] + 0.15*F["z_import_reliance"]

# 5) Quadrants pour une lecture “où aller / où éviter”
pc1_med = F["PC1"].median()
pc2_med = F["PC2"].median()

def segment(row):
    if row["PC1"] >= pc1_med and row["PC2"] >= pc2_med:
        return "A_Prioritaire (haut volume & haute intensité)"
    if row["PC1"] < pc1_med and row["PC2"] >= pc2_med:
        return "B_Niche premium (faible volume, haute intensité)"
    if row["PC1"] >= pc1_med and row["PC2"] < pc2_med:
        return "C_Mass market (haut volume, intensité + faible)"
    return "D_Aviter/Surveiller (faible volume & intensité)"

F["Segment"] = F.apply(segment, axis=1)

# 6) Sorties utiles
# 6a) Top 20 pays à cibler (score)
top20 = F.sort_values("Attractivite", ascending=False).head(20)[
    ["Zone", "Année", "Attractivite", "PC1", "PC2", "import_reliance", "kg_per_cap", "kcal_per_cap", "Segment"]
]
print("\n=== TOP 20 pays (score d'attractivité) ===")
print(top20.to_string(index=False))

# 6b) Pays à éviter/surveiller (quadrant D)
avoid = F[F["Segment"].str.startswith("D_")].sort_values("Attractivite").head(20)[
    ["Zone", "Année", "Attractivite", "PC1", "PC2", "import_reliance", "kg_per_cap", "kcal_per_cap", "Segment"]
]
print("\n=== À ÉVITER / SURVEILLER (extraits) ===")
print(avoid.to_string(index=False))

# 6c) Export CSV pour analyse/partage
F.sort_values("Attractivite", ascending=False).to_csv("Classement_pays_poulet.csv", index=False)
print("\nClassement détaillé exporté -> Classement_pays_poulet.csv")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# =========================
# Nuage Volume (PC1) × Intensité (PC2)
# Top 5 par segment + France obligatoire, couleurs par segment
# Légende en dehors du graphique (à droite)
# =========================

df = res.copy()

# 0) Nettoyage minimal
df = df.dropna(subset=["PC1", "PC2"]).copy()
df["Zone"] = df["Zone"].astype(str)

# 1) Retirer "Chine, continentale"
# mask_rm = df["Zone"].str.strip().str.casefold().eq("chine, continentale")
mask_rm = df["Zone"].astype(str).str.strip().str.casefold().isin(["chine, continentale", "chine"])
df = df[~mask_rm].copy()

# 2) Médianes pour découper les quadrants (segments)
x_med = float(df["PC1"].median())
y_med = float(df["PC2"].median())

def segment_row(row):
    if row["PC1"] >= x_med and row["PC2"] >= y_med:
        return "A_Prioritaire (haut volume & haute intensité)"
    if row["PC1"] <  x_med and row["PC2"] >= y_med:
        return "B_Niche premium (faible volume, haute intensité)"
    if row["PC1"] >= x_med and row["PC2"] <  y_med:
        return "C_Mass market (haut volume, intensité + faible)"
    return "D_Aviter/Surveiller (faible volume & intensité)"

df["Segment"] = df.apply(segment_row, axis=1)

# 3) Score de proéminence dans le quadrant = distance à l'intersection des médianes
df["_dist_med"] = (df["PC1"] - x_med).abs() + (df["PC2"] - y_med).abs()

# 4) Top 5 par segment (A/B/C/D)
segments_ordre = [
    "A_Prioritaire (haut volume & haute intensité)",
    "B_Niche premium (faible volume, haute intensité)",
    "C_Mass market (haut volume, intensité + faible)",
    "D_Aviter/Surveiller (faible volume & intensité)",
]

tops = []
TOP_K = 5
for seg in segments_ordre:
    seg_df = df[df["Segment"] == seg].sort_values("_dist_med", ascending=False)
    tops.append(seg_df.head(TOP_K))

sel = pd.concat(tops, axis=0)

# 5) Forcer l'inclusion de la France si absente (et si elle existe dans df)
has_fr = df["Zone"].str.strip().str.casefold().eq("france").any()
if has_fr and not sel["Zone"].str.strip().str.casefold().eq("france").any():
    france_row = df[df["Zone"].str.strip().str.casefold().eq("france")].copy()
    sel = pd.concat([sel, france_row], axis=0)
    sel = sel.drop_duplicates(subset=["Zone"], keep="first")

# 6) Palette par segment (couleurs cohérentes)
colors = {
    "A_Prioritaire (haut volume & haute intensité)"      : "#2ca02c",  # vert
    "B_Niche premium (faible volume, haute intensité)"    : "#9467bd",  # violet
    "C_Mass market (haut volume, intensité + faible)"     : "#ff7f0e",  # orange
    "D_Aviter/Surveiller (faible volume & intensité)"     : "#eb1a00",  # rouge
}

# 7) Plot limité au sous-ensemble sélectionné, légende hors cadre
fig, ax = plt.subplots(figsize=(10, 6))

for seg in segments_ordre:
    sub = sel[sel["Segment"] == seg]
    if sub.empty:
        continue
    ax.scatter(sub["PC1"], sub["PC2"], label=seg, s=60, color=colors.get(seg, None))

# Lignes médianes (références)
ax.axvline(x_med, linestyle="--", linewidth=1)
ax.axhline(y_med, linestyle="--", linewidth=1)

# Axes et titre
ax.set_xlabel("Volume (PC1) →")
ax.set_ylabel("Intensité (PC2) ↑")
ax.set_title("Marché du poulet — Volume × Intensité (Top 5 par segment)")

# Quadrants (labels)
xmin, xmax = ax.get_xlim()
ymin, ymax = ax.get_ylim()
ax.text((x_med + xmax)/2, (y_med + ymax)/2, "A  Prioritaire", ha="center", va="center")
ax.text((xmin + x_med)/2, (y_med + ymax)/2, "B  Niche premium", ha="center", va="center")
ax.text((x_med + xmax)/2, (ymin + y_med)/2, "C  Mass-market", ha="center", va="center")
ax.text((xmin + x_med)/2, (ymin + y_med)/2, "D  Surveiller", ha="center", va="center")

# Annotation des points sélectionnés
# - France mise en avant (marqueur cercle vide + étoile dans le label)
fr_idx = set(sel.index[sel["Zone"].str.strip().str.casefold().eq("france")])
for idx, r in sel.iterrows():
    txt = r["Zone"] + (" ★" if idx in fr_idx else "")
    xy = (r["PC1"], r["PC2"])
    if idx in fr_idx:
        ax.scatter([r["PC1"]], [r["PC2"]], s=120, facecolors='none', edgecolors='black', linewidths=2)
        ax.annotate(txt, xy, fontsize=9, fontweight="bold")
    else:
        ax.annotate(txt, xy, fontsize=8)

# Légende EN DEHORS du graphique (à droite)
# - loc='center left' + bbox_to_anchor place la légende à côté
# leg = ax.legend(title="Segment", loc='center left', bbox_to_anchor=(1.02, 0.5), frameon=True)
# plt.tight_layout()  # ajuste les marges pour ne pas rogner le plot
# plt.savefig("Nuage_Volume_Intensite_Top5_segments.png", dpi=150, bbox_inches="tight")
# plt.show()

# 8) Récap en console
print("\n=== RÉCAP : Top 5 par segment (après exclusion de 'Chine, continentale') ===")
print(f"- Médiane PC1 = {x_med:.3f} | Médiane PC2 = {y_med:.3f}")
print(f"- TOP_K = {TOP_K}")

# Statut France
if has_fr:
    in_plot = sel["Zone"].str.strip().str.casefold().eq("france").any()
    print(f"- France présente dans le plot : {'OUI' if in_plot else 'NON'}")
else:
    print("- France absente des données (non trouvée dans 'Zone').")

# Détail par segment
for seg in segments_ordre:
    sub = sel[sel["Segment"] == seg].copy()
    if sub.empty:
        print(f"\n[{seg}] — aucun pays sélectionné.")
        continue
    sub = sub.sort_values("_dist_med", ascending=False)
    cols_show = ["Zone", "PC1", "PC2"]
    print(f"\n[{seg}] — {len(sub)} pays affichés (Top {min(TOP_K, len(sub))}) :")
    print(sub[cols_show].round(3).to_string(index=False))

print("\nNote : 'Chine, continentale' exclue explicitement du visuel.")
print("Image exportée : Nuage_Volume_Intensite_Top5_segments.png")

# 16) Nuage Volume × Intensité (PC1–PC2) — VISION GLOBALE PAR RÉGION
#     - Chaque point = une région (PC1/PC2 agrégés par région)
#     - Quadrants = médianes calculées sur les régions
#     - Couleurs par segment (A/B/C/D), légende à droite
#     - Filtre: uniquement pays dont Code Élément/Domaine == 'donneesmondiales.com'
#     - Exclusions: "Chine, continentale" + Region == "Inconnu"

# --- Détection de la colonne de code source (préférence: 'Code Élément', fallback: 'Code Domaine')
# Retirer explicitement la région "Inconnu"
mask_inconnu = df_reg["Region"].astype(str).str.strip().str.casefold().eq("inconnu")
n_inconnu = int(mask_inconnu.sum())
if n_inconnu > 0:
    print(f"[Info] {n_inconnu} ligne(s) avec Region='Inconnu' retirée(s).")
df_reg = df_reg[~mask_inconnu].copy()

# Puis on retire les Region manquantes
df_reg = df_reg.dropna(subset=["Region"]).copy()

dm_col_try = ["Code Élément", "Code Domaine"]
dm_col = None
for c in dm_col_try:
    try:
        _tmp = pd.read_csv(path, usecols=["Zone", c], nrows=0)
        dm_col = c
        break
    except Exception:
        continue
if dm_col is None:
    raise ValueError("Aucune colonne 'Code Élément' ou 'Code Domaine' trouvée dans le CSV.")

# --- Pays autorisés: ceux qui ont 'donneesmondiales.com' dans la colonne dm_col
dm_df = pd.read_csv(
    path,
    usecols=["Zone", dm_col],
    dtype={"Zone": "string", dm_col: "string"},
    low_memory=True,
)
allowed_zones = (
    dm_df.loc[
        dm_df[dm_col].astype("string").str.strip().str.casefold() == "donneesmondiales.com", "Zone"
    ].dropna().unique().tolist()
)
print(f"[Info] Pays avec {dm_col} == 'donneesmondiales.com' : {len(allowed_zones)}")

# --- Mapping Zone -> Region
reg_df = pd.read_csv(
    path,
    usecols=["Zone", "Region"],
    dtype={"Zone": "string", "Region": "string"},
    low_memory=True,
)
reg_df = reg_df.dropna(subset=["Zone"]).drop_duplicates(subset=["Zone"])
zone_to_region = reg_df.set_index("Zone")["Region"].to_dict()

# --- Base scores ACP par pays -> filtrage + ajout région
df_reg = res.copy()  # suppose: colonnes ['Zone','Année','PC1','PC2']
df_reg = df_reg.dropna(subset=["PC1", "PC2"]).copy()
df_reg["Zone"] = df_reg["Zone"].astype(str)

# Exclure Chine
mask_rm = df_reg["Zone"].str.strip().str.casefold().isin(["chine, continentale", "chine"])
df_reg = df_reg[~mask_rm].copy()

# Filtre zones autorisées "donneesmondiales.com"
df_reg = df_reg[df_reg["Zone"].isin(allowed_zones)].copy()
if df_reg.empty:
    raise ValueError("Aucune donnée après filtre 'donneesmondiales.com' pour la vision par région.")

# Ajout de la région
df_reg["Region"] = df_reg["Zone"].map(zone_to_region)

# Retirer explicitement la région "Inconnu"
mask_inconnu = df_reg["Region"].astype(str).str.strip().str.casefold().eq("inconnu")
n_inconnu = int(mask_inconnu.sum())
if n_inconnu > 0:
    print(f"[Info] {n_inconnu} ligne(s) avec Region='Inconnu' retirée(s).")
df_reg = df_reg[~mask_inconnu].copy()

# Retirer les Region manquantes
missing_regions = int(df_reg["Region"].isna().sum())
if missing_regions > 0:
    print(f"[Info] {missing_regions} pays sans 'Region' — ignorés.")
df_reg = df_reg.dropna(subset=["Region"]).copy()

# --- Agrégation au niveau RÉGION (médiane; remplace par 'mean' si souhaité)
agg = (
    df_reg.groupby("Region", as_index=False)
          .agg(PC1=("PC1", "median"), PC2=("PC2", "median"), N=("Zone", "nunique"))
          .sort_values("Region")
          .reset_index(drop=True)
)
if agg.shape[0] < 2:
    raise ValueError("Trop peu de régions après agrégation pour tracer un nuage.")

# --- Segmentation des RÉGIONS via médianes inter-régions
x_med = float(agg["PC1"].median())
y_med = float(agg["PC2"].median())

def segment_row_region(row):
    if row["PC1"] >= x_med and row["PC2"] >= y_med:
        return "A_Prioritaire (haut volume & haute intensité)"
    if row["PC1"] <  x_med and row["PC2"] >= y_med:
        return "B_Niche premium (faible volume, haute intensité)"
    if row["PC1"] >= x_med and row["PC2"] <  y_med:
        return "C_Mass market (haut volume, intensité + faible)"
    return "D_Aviter/Surveiller (faible volume & intensité)"

agg["Segment"] = agg.apply(segment_row_region, axis=1)
agg["_dist_med"] = (agg["PC1"] - x_med).abs() + (agg["PC2"] - y_med).abs()

# --- Couleurs par segment
segments_ordre = [
    "A_Prioritaire (haut volume & haute intensité)",
    "B_Niche premium (faible volume, haute intensité)",
    "C_Mass market (haut volume, intensité + faible)",
    "D_Aviter/Surveiller (faible volume & intensité)",
]
colors = {
    "A_Prioritaire (haut volume & haute intensité)"      : "#2ca02c",  # vert
    "B_Niche premium (faible volume, haute intensité)"    : "#9467bd",  # violet
    "C_Mass market (haut volume, intensité + faible)"     : "#ff7f0e",  # orange
    "D_Aviter/Surveiller (faible volume & intensité)"     : "#eb1a00",  # rouge
}

# --- PLOT : un point = une RÉGION
fig, ax = plt.subplots(figsize=(10, 6))
for seg in segments_ordre:
    sub = agg[agg["Segment"] == seg]
    if sub.empty:
        continue
    ax.scatter(sub["PC1"], sub["PC2"], label=seg, s=80, color=colors.get(seg, None))

# Lignes médianes (références globales entre régions)
ax.axvline(x_med, linestyle="--", linewidth=1)
ax.axhline(y_med, linestyle="--", linewidth=1)

# Axes et titre
ax.set_xlabel("Volume (PC1) →")
ax.set_ylabel("Intensité (PC2) ↑")
ax.set_title("Marché du poulet — Volume × Intensité — Vision globale par RÉGION (sans 'Inconnu')")

# Quadrants (labels)
xmin, xmax = ax.get_xlim()
ymin, ymax = ax.get_ylim()
ax.text((x_med + xmax)/2, (y_med + ymax)/2, "A  Prioritaire", ha="center", va="center")
ax.text((xmin + x_med)/2, (y_med + ymax)/2, "B  Niche premium", ha="center", va="center")
ax.text((x_med + xmax)/2, (ymin + y_med)/2, "C  Mass-market", ha="center", va="center")
ax.text((xmin + x_med)/2, (ymin + y_med)/2, "D  Surveiller", ha="center", va="center")

# Annotations: nom de la région
for _, r in agg.iterrows():
    ax.annotate(r["Region"], (r["PC1"], r["PC2"]), fontsize=9)

# Légende à droite
# ax.legend(title="Segment", loc='center left', bbox_to_anchor=(1.02, 0.5), frameon=True)

# Export
out_path = "Nuage_Volume_Intensite_Regions_sans_Inconnu.png"
plt.tight_layout()
plt.savefig(out_path, dpi=150, bbox_inches="tight")
plt.show()

# --- RÉCAP console
print("\n=== RÉCAP — Vision globale par RÉGION (sans 'Inconnu') ===")
print(f"- Régions: {agg.shape[0]} | Médiane PC1 = {x_med:.3f} | Médiane PC2 = {y_med:.3f}")
for seg in segments_ordre:
    sub = agg[agg["Segment"] == seg].sort_values("_dist_med", ascending=False)
    if sub.empty:
        print(f"\n[{seg}] — aucune région.")
        continue
    print(f"\n[{seg}] — {len(sub)} région(s) :")
    print(sub[["Region", "PC1", "PC2", "N"]].round(3).to_string(index=False))

print("\nNote : 'Chine, continentale' et 'Inconnu' exclus. Fichier exporté : Nuage_Volume_Intensite_Regions_sans_Inconnu.png")

import numpy as np
import matplotlib.pyplot as plt

df = res.copy()

# Retirer la ligne "Chine, continentale" (robuste à la casse et aux espaces)
# mask_rm = df["Zone"].astype(str).str.strip().str.casefold().eq("chine, continentale")
mask_rm = df["Zone"].astype(str).str.strip().str.casefold().isin(["chine, continentale", "chine"])
df = df[~mask_rm].copy()

# 1) Médians (calculées APRÈS filtrage)
x = df["PC1"]
y = df["PC2"]
x_med = float(x.median())
y_med = float(y.median())

# 2) Plot
plt.figure()
plt.scatter(x, y)  # 1 point = 1 pays

# 3) Lignes médianes (quadrants)
plt.axvline(x_med, linestyle="--", linewidth=1)
plt.axhline(y_med, linestyle="--", linewidth=1)

# 4) Axes et titre (étiquettes "grand public")
plt.xlabel("Volume (PC1) →")
plt.ylabel("Intensité (PC2) ↑")
plt.title("Marchés du poulet — Volume × Intensité (quadrants)")

# 5) Quadrants : placer des labels lisibles
xmin, xmax = plt.xlim()
ymin, ymax = plt.ylim()
plt.text((x_med + xmax)/2, (y_med + ymax)/2,
         "A  Prioritaire", ha="center", va="center")
plt.text((xmin + x_med)/2, (y_med + ymax)/2,
         "B  Niche premium", ha="center", va="center")
plt.text((x_med + xmax)/2, (ymin + y_med)/2,
         "C  Mass-market", ha="center", va="center")
plt.text((xmin + x_med)/2, (ymin + y_med)/2,
         "D  Surveiller", ha="center", va="center")

# 6) Annoter les 20 pays les plus "éloignés" du centre (lecture rapide)
df["_dist"] = (df["PC1"] - x_med).abs() + (df["PC2"] - y_med).abs()
for _, r in df.nlargest(20, "_dist")[["Zone", "PC1", "PC2"]].iterrows():
    plt.annotate(r["Zone"], (r["PC1"], r["PC2"]))  # cf. annotate Matplotlib :contentReference[oaicite:1]{index=1}

plt.grid(True)
plt.show()

"""# Methode CAH"""

# ============================================
# CAH (Ward) sur les scores ACP (PC1..PCm)
# - retire "Chine, continentale"
# - dendrogramme + coupe en k classes
# - scatter PC1×PC2 coloré par cluster + récap
# ============================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import linkage, dendrogram, fcluster  # SciPy
from sklearn.cluster import AgglomerativeClustering  # scikit-learn

# 0) Préparer la matrice de clustering à partir des scores ACP
#    -> garder assez de composantes pour ~80% de variance (min 2)
cumvar = np.cumsum(explained)                 # explained = pca.explained_variance_ratio_
n_keep = int(np.searchsorted(cumvar, 0.80) + 1)
n_keep = max(2, min(n_keep, X_pca.shape[1]))  # borne de sécurité 2..n_components
scores = pd.DataFrame(X_pca[:, :n_keep],
                      columns=[f"PC{i+1}" for i in range(n_keep)])

# 1) Joindre les pays & RETIRER "Chine, continentale"
M = pd.concat([res[["Zone"]].reset_index(drop=True), scores], axis=1).copy()
# mask_rm = M["Zone"].str.strip().str.casefold().eq("chine, continentale")
mask_rm = M["Zone"].str.strip().str.casefold().isin(["chine, continentale", "chine"])
M = M[~mask_rm].reset_index(drop=True)

# 2) CAH (Ward + euclidien) — via SciPy pour le dendrogramme
Z = linkage(M.iloc[:, 1:].to_numpy(), method="ward", metric="euclidean")  # SciPy linkage
#    NB : Ward minimise l'augmentation de variance intra à chaque fusion.  # réf. méthode

# 3) Dendrogramme (tronqué pour lisibilité si besoin)
plt.figure(figsize=(10, 5))
dendrogram(
    Z,
    labels=M["Zone"].to_list(),
    leaf_rotation=90,
    leaf_font_size=8,
    truncate_mode=None,   # "lastp" et p=50 si trop de pays
    # p=50,
    color_threshold=None  # tu peux mettre un seuil pour colorer les branches
)
plt.title(f"Dendrogramme (Ward, euclidien) — {n_keep} PC retenues (~{cumvar[n_keep-1]*100:.1f}% var.)")
plt.ylabel("Distance de fusion")
plt.tight_layout()
plt.show()

# 4) Choisir k (nb de classes) et affecter les clusters
#    OPTION A : fixer k (ex. 4 classes)
K = 4
labels = fcluster(Z, t=K, criterion="maxclust")

#    OPTION B : couper par un seuil de distance (ex. t=Z[:,2] quantile 0.9)
# thr = np.quantile(Z[:, 2], 0.90)
# labels = fcluster(Z, t=thr, criterion="distance")

clusters = pd.DataFrame({"Zone": M["Zone"], "Cluster": labels})

# 5) Scatter PC1×PC2 coloré par cluster (pays)
palette = plt.cm.get_cmap("tab10", len(np.unique(labels)))  # palette discrète
plt.figure(figsize=(9, 6))
for c in np.unique(labels):
    sub = M[clusters["Cluster"] == c]
    plt.scatter(sub["PC1"], sub["PC2"], s=60, label=f"Cluster {c}", color=palette(c-1))
plt.axhline(0, linewidth=0.5); plt.axvline(0, linewidth=0.5)
plt.xlabel("PC1 (Volume)"); plt.ylabel("PC2 (Intensité)")
plt.title(f"CAH — Projection PC1×PC2 (k={K})")
plt.legend(loc="best", frameon=True)
plt.grid(True, linestyle="--", linewidth=0.5)
plt.tight_layout()
plt.show()

# 6) Récap console : tailles de clusters + pays par cluster
print(f"\n=== CAH (Ward, euclidien) — {n_keep} PC (≈{cumvar[n_keep-1]*100:.1f}% var.) — k={K} ===")
sizes = clusters.value_counts("Cluster").sort_index()
print("\nTaille des clusters :")
print(sizes.to_string())

# Top pays par cluster (ceux les plus "au bord" sur PC1/PC2, indicatif)
M2 = M.join(clusters["Cluster"])
M2["_dist"] = M2["PC1"].abs() + M2["PC2"].abs()
for c in sorted(M2["Cluster"].unique()):
    top = M2[M2["Cluster"]==c].sort_values("_dist", ascending=False).head(10)
    print(f"\n[Cluster {c}] Pays marquants (PC1/PC2 éloignés) :")
    print(top[["Zone", "PC1", "PC2"]].round(3).to_string(index=False))

# 7) (Optionnel) Décrire les clusters sur quelques variables "métier"
#    -> si pivot_last a ces colonnes, on calcule la médiane par cluster
try:
    # On suppose que pivot_last a encore toutes les lignes (mêmes pays que 'res')
    meta = pivot_last.set_index("Zone")
    desc_cols = [
        "production",
        "nourriture",
        "importations - quantité",
        "exportations - quantité",
        "disponibilité alimentaire en quantité (kg/personne/an)",
        "disponibilité alimentaire (kcal/personne/jour)",
    ]
    dispo = [c for c in desc_cols if c in meta.columns]
    cl_desc = meta.join(clusters.set_index("Zone")).groupby("Cluster")[dispo].median().round(2)
    if len(dispo) > 0:
        print("\nMédianes par cluster (variables clés) :")
        print(cl_desc.to_string())
except Exception as e:
    print("\n[Info] Description par variables non calculée :", e)

# 17) CAH (Ward) sur les RÉGIONS à partir des scores ACP (PC1..PCm)
#     - filtre 'donneesmondiales.com' (Code Élément ou Code Domaine)
#     - retire "Chine, continentale" (+ "Chine")
#     - retire Region == "Inconnu" et Region manquante
#     - agrège les PC par RÉGION (médiane)
#     - dendrogramme + coupe en k classes
#     - scatter PC1×PC2 (un point = une RÉGION) coloré par cluster + récap

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import linkage, dendrogram, fcluster  # SciPy

# ---------- 0) Choisir combien de composantes garder (~80% variance, min 2) ----------
cumvar = np.cumsum(explained)                 # explained = pca.explained_variance_ratio_
n_keep = int(np.searchsorted(cumvar, 0.80) + 1)
n_keep = max(2, min(n_keep, X_pca.shape[1]))  # borne 2..n_components

scores = pd.DataFrame(X_pca[:, :n_keep],
                      columns=[f"PC{i+1}" for i in range(n_keep)])
M_country = pd.concat([res[["Zone"]].reset_index(drop=True), scores], axis=1).copy()

# ---------- 1) Filtrer les pays autorisés via 'donneesmondiales.com' ----------
# Détection de la colonne (préférence 'Code Élément', fallback 'Code Domaine')
dm_col = None
for c in ["Code Élément", "Code Domaine"]:
    try:
        _ = pd.read_csv(path, usecols=["Zone", c], nrows=0)
        dm_col = c
        break
    except Exception:
        continue
if dm_col is None:
    raise ValueError("Aucune colonne 'Code Élément' ou 'Code Domaine' trouvée dans le CSV.")

dm_df = pd.read_csv(
    path,
    usecols=["Zone", dm_col],
    dtype={"Zone": "string", dm_col: "string"},
    low_memory=True,
)
allowed_zones = (
    dm_df.loc[
        dm_df[dm_col].astype("string").str.strip().str.casefold() == "donneesmondiales.com", "Zone"
    ].dropna().unique().tolist()
)
M_country = M_country[M_country["Zone"].isin(allowed_zones)].copy()

# ---------- 2) Exclure "Chine, continentale" (+ "Chine") ----------
mask_rm = M_country["Zone"].astype(str).str.strip().str.casefold().isin(["chine, continentale", "chine"])
M_country = M_country[~mask_rm].reset_index(drop=True)

# ---------- 3) Ajouter la RÉGION, retirer "Inconnu"/NaN ----------
reg_df = pd.read_csv(
    path,
    usecols=["Zone", "Region"],
    dtype={"Zone": "string", "Region": "string"},
    low_memory=True,
).dropna(subset=["Zone"]).drop_duplicates(subset=["Zone"])
zone_to_region = reg_df.set_index("Zone")["Region"].to_dict()

M_country["Region"] = M_country["Zone"].map(zone_to_region)

mask_inconnu = M_country["Region"].astype(str).str.strip().str.casefold().eq("inconnu")
if mask_inconnu.any():
    print(f"[Info] {int(mask_inconnu.sum())} ligne(s) Region='Inconnu' retirée(s).")
M_country = M_country[~mask_inconnu].copy()
M_country = M_country.dropna(subset=["Region"]).copy()

# ---------- 4) AGRÉGER au niveau RÉGION (médiane des PC) ----------
pc_cols = [f"PC{i+1}" for i in range(n_keep)]
M_region = (
    M_country.groupby("Region")
             .agg({**{c: "median" for c in pc_cols}, "Zone": "nunique"})
             .rename(columns={"Zone": "N"})
             .reset_index()
)

if M_region.shape[0] < 2:
    raise ValueError("Trop peu de régions après agrégation pour une CAH.")


# ---------- 5) CAH (Ward + euclidien) sur les RÉGIONS ----------
X_reg = M_region[[f"PC{i+1}" for i in range(n_keep)]].to_numpy()
Z = linkage(X_reg, method="ward", metric="euclidean")  # Ward ≡ variance minimale (euclidien)

# ---------- 6) Dendrogramme des RÉGIONS ----------
plt.figure(figsize=(10, 5))
dendrogram(
    Z,
    labels=M_region["Region"].to_list(),
    leaf_rotation=90,          # lisibilité
    leaf_font_size=8,
    truncate_mode=None,        # "lastp"/p=.. si trop de régions
    color_threshold=None
)
plt.title(f"Dendrogramme RÉGIONS (Ward, euclidien) — {n_keep} PC (~{cumvar[n_keep-1]*100:.1f}% var.)")
plt.ylabel("Distance de fusion")
plt.tight_layout()
plt.show()

# ---------- 7) Coupe en k classes ----------
K = 4  # à ajuster si besoin
labels = fcluster(Z, t=K, criterion="maxclust")  # 'maxclust' = ≤ K clusters
clusters_reg = pd.DataFrame({"Region": M_region["Region"], "Cluster": labels})

# ---------- 8) Scatter PC1×PC2 (un point = une RÉGION) coloré par cluster ----------
palette = plt.cm.get_cmap("tab10", len(np.unique(labels)))
plt.figure(figsize=(9, 6))
for c in np.unique(labels):
    sub = M_region[clusters_reg["Cluster"] == c]
    plt.scatter(sub["PC1"], sub["PC2"], s=80, label=f"Cluster {c}", color=palette(c-1))
plt.axhline(0, linewidth=0.5); plt.axvline(0, linewidth=0.5)
plt.xlabel("PC1 (Volume)"); plt.ylabel("PC2 (Intensité)")
plt.title(f"CAH — RÉGIONS — Projection PC1×PC2 (k={K})")
plt.legend(loc="best", frameon=True)
plt.grid(True, linestyle="--", linewidth=0.5)
plt.tight_layout()
plt.show()

# ---------- 9) Récap console ----------
print(f"\n=== CAH RÉGIONS (Ward, euclidien) — {n_keep} PC (≈{cumvar[n_keep-1]*100:.1f}% var.) — k={K} ===")
sizes = clusters_reg.value_counts("Cluster").sort_index()
print("\nTaille des clusters (nombre de RÉGIONS) :")
print(sizes.to_string())

# Régions marquantes par cluster (éloignées de l'origine PC1/PC2)
MR = M_region.join(clusters_reg.set_index("Region"), on="Region")
MR["_dist"] = MR["PC1"].abs() + MR["PC2"].abs()
for c in sorted(MR["Cluster"].unique()):
    top = MR[MR["Cluster"]==c].sort_values("_dist", ascending=False).head(10)
    print(f"\n[Cluster {c}] Régions marquantes (|PC1|+|PC2| élevé) :")
    print(top[["Region", "PC1", "PC2", "N"]].round(3).to_string(index=False))

# ---------- 10) (Optionnel) Décrire les clusters sur variables "métier" ----------
# On agrège d'abord pivot_last au niveau RÉGION (médianes par région), puis médianes par cluster.
try:
    meta = pivot_last.copy()
    meta["Region"] = meta["Zone"].map(zone_to_region)
    # Même exclusions / filtres que plus haut
    mask_rm2 = meta["Zone"].astype(str).str.strip().str.casefold().isin(["chine, continentale", "chine"])
    meta = meta[~mask_rm2].copy()
    meta = meta[meta["Zone"].isin(allowed_zones)].copy()
    mask_inc2 = meta["Region"].astype(str).str.strip().str.casefold().eq("inconnu")
    meta = meta[~mask_inc2].dropna(subset=["Region"]).copy()

    desc_cols = [
        "production",
        "nourriture",
        "importations - quantité",
        "exportations - quantité",
        "disponibilité alimentaire en quantité (kg/personne/an)",
        "disponibilité alimentaire (kcal/personne/jour)",
    ]
    dispo = [c for c in desc_cols if c in meta.columns]
    if dispo:
        meta_reg = meta.groupby("Region")[dispo].median()
        cl_desc = meta_reg.join(clusters_reg.set_index("Region")).groupby("Cluster")[dispo].median().round(2)
        print("\nMédianes par cluster (variables clés, agrégées au niveau RÉGION) :")
        print(cl_desc.to_string())
except Exception as e:
    print("\n[Info] Description par variables non calculée :", e)

# ============================================
# K-means sur les scores ACP (PC1..PCm)
# - retire "Chine, continentale" ET "Chine"
# - sélection de k par silhouette (2..10) + coude (inertie)
# - scatter PC1×PC2 coloré par cluster + récap + export CSV
# ============================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# 0) Vérifs rapides : on suppose déjà disponibles -> res, X_pca, explained
assert 'res' in globals() and 'X_pca' in globals() and 'explained' in globals(), \
    "Il faut exécuter l'ACP avant (pour avoir res, X_pca, explained)."

# 1) Choisir le nombre de composantes ACP à garder (~80% var., min=2)
cumvar = np.cumsum(explained)
n_keep = int(np.searchsorted(cumvar, 0.80) + 1)
n_keep = max(2, min(n_keep, X_pca.shape[1]))  # bornes sécurité
scores = pd.DataFrame(X_pca[:, :n_keep], columns=[f"PC{i+1}" for i in range(n_keep)])

# 2) Joindre les pays & RETIRER "Chine, continentale" + "Chine"
M = pd.concat([res[["Zone", "Année"]].reset_index(drop=True), scores], axis=1).copy()
mask_rm = M["Zone"].str.strip().str.casefold().isin(["chine, continentale", "chine"])
M = M[~mask_rm].reset_index(drop=True)

Xk = M.iloc[:, 2:].to_numpy()  # matrice des PC retenues

# 3) Sélection de k par silhouette (k = 2..10) + calcul inertie (coude)
ks = list(range(2, min(10, len(M)) + 1))
sil_vals = []
inertias = []

# Petite compatibilité sklearn : n_init='auto' (>=1.4) ou n_init=10 (versions plus anciennes)  :contentReference[oaicite:1]{index=1}
def fit_kmeans(X, k, random_state=42):
    try:
        return KMeans(n_clusters=k, init='k-means++', n_init='auto', random_state=random_state).fit(X)
    except TypeError:
        return KMeans(n_clusters=k, init='k-means++', n_init=10, random_state=random_state).fit(X)

for k in ks:
    km = fit_kmeans(Xk, k)
    inertias.append(km.inertia_)                       # somme des distances intra-classes (WSS)
    sil = silhouette_score(Xk, km.labels_) if k > 1 else np.nan  # [-1,1], plus haut = mieux  :contentReference[oaicite:2]{index=2}
    sil_vals.append(sil)

# Choix auto : k avec silhouette max (en cas d’ex æquo, on prend le plus petit k)
k_best = int(ks[int(np.nanargmax(sil_vals))])

# 4) Entraînement final K-means avec k_best
km_final = fit_kmeans(Xk, k_best)
labels = km_final.labels_
centers = km_final.cluster_centers_  # centres dans l’espace des PC retenues

# 5) Sorties / export
out = M.copy()
out["Cluster"] = labels + 1  # clusters 1..k
out.to_csv("KMEANS_clusters_scoresPCA.csv", index=False)
print(f"\n=== K-means (PC1..PC{n_keep}) — k choisi par silhouette = {k_best} ===")
print(f"Variance expliquée cumulée par PC1..PC{n_keep} : {cumvar[n_keep-1]*100:.1f}%")
print("\nSilhouette par k (2..10) :")
for k, s in zip(ks, sil_vals):
    print(f" k={k:<2} -> silhouette={s:.3f}")
sizes = out.value_counts("Cluster").sort_index()
print("\nTaille des clusters :")
print(sizes.to_string())

# 6) Graphiques : Courbes silhouette & inertie (coude)
plt.figure()
plt.plot(ks, sil_vals, marker="o")
plt.xlabel("k (nombre de clusters)")
plt.ylabel("Silhouette moyenne [-1,1]")
plt.title("Sélection de k — Silhouette (K-means)")
plt.grid(True, linestyle="--", linewidth=0.5)
plt.show()

plt.figure()
plt.plot(ks, inertias, marker="o")
plt.xlabel("k (nombre de clusters)")
plt.ylabel("Inertie (WSS)")
plt.title("Sélection de k — Coude (Inertie)")
plt.grid(True, linestyle="--", linewidth=0.5)
plt.show()

# 7) Scatter PC1×PC2 coloré par cluster (légende en dehors)
plt.figure(figsize=(9, 6))
for c in sorted(out["Cluster"].unique()):
    sub = out[out["Cluster"] == c]
    plt.scatter(sub["PC1"], sub["PC2"], s=60, label=f"Cluster {c}")
plt.axhline(0, linewidth=0.5); plt.axvline(0, linewidth=0.5)
plt.xlabel("PC1 (Volume)"); plt.ylabel("PC2 (Intensité)")
plt.title(f"K-means — Projection PC1×PC2 (k={k_best})")
# légende à droite
plt.legend(title="Cluster", loc="center left", bbox_to_anchor=(1.02, 0.5), frameon=True)
plt.tight_layout()
plt.savefig("KMEANS_PC1xPC2.png", dpi=150, bbox_inches="tight")
plt.show()

# 8) (Optionnel) Pays “centraux” de chaque cluster (les plus proches du centre du cluster en PC)
from sklearn.metrics import pairwise_distances_argmin_min
idxs, dists = pairwise_distances_argmin_min(Xk, centers)
M2 = out.copy()
M2["_dist_center"] = dists
for c in sorted(out["Cluster"].unique()):
    tmp = M2[M2["Cluster"] == c].sort_values("_dist_center").head(10)
    print(f"\n[Cluster {c}] 10 pays les + proches du centre (PC-space) :")
    print(tmp[["Zone", "Année", "PC1", "PC2", "_dist_center"]].round(3).to_string(index=False))
print()
print("\n--- PARAMÈTRES EFFECTIFS ---")
print(f"k choisi (silhouette): {k_best}")
print(f"init: k-means++ | n_init: {km_final.n_init}")
print(f"random_state: 42 | max_iter: {km_final.max_iter} | tol: {km_final.tol}")
print(f"Nb de PC utilisées: {n_keep} (≈{cumvar[n_keep-1]*100:.1f}% de variance)")
print()
print("\nFichiers exportés :")
print(" - KMEANS_clusters_scoresPCA.csv")
print(" - KMEANS_PC1xPC2.png")

# 18) K-means sur les RÉGIONS (à partir des scores ACP PC1..PCm)
#     - filtre: Code Élément/Domaine == 'donneesmondiales.com'
#     - exclusions: "Chine, continentale" + "Chine" + Region == "Inconnu"/NaN
#     - agrégation par région (médiane des PC)
#     - sélection de k par silhouette (2..min(10, nb_régions-1)) + coude (inertie)
#     - scatter PC1×PC2 (1 point = 1 région) + légende à droite
#     - export CSV des clusters de régions

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, pairwise_distances_argmin_min

# --- Vérifs ---
assert 'res' in globals() and 'X_pca' in globals() and 'explained' in globals() and 'path' in globals(), \
    "Il faut exécuter l'ACP avant (res, X_pca, explained) et définir 'path'."

# 1) Choix du nombre de composantes à garder (~80% var., min=2)
cumvar = np.cumsum(explained)
n_keep = int(np.searchsorted(cumvar, 0.80) + 1)
n_keep = max(2, min(n_keep, X_pca.shape[1]))
pc_cols = [f"PC{i+1}" for i in range(n_keep)]
scores = pd.DataFrame(X_pca[:, :n_keep], columns=pc_cols)

# 2) Scores pays + filtres de base (Chine)
M_country = pd.concat([res[["Zone", "Année"]].reset_index(drop=True), scores], axis=1).copy()
M_country["Zone"] = M_country["Zone"].astype(str)
mask_rm = M_country["Zone"].str.strip().str.casefold().isin(["chine, continentale", "chine"])
M_country = M_country[~mask_rm].reset_index(drop=True)

# 3) Filtre 'donneesmondiales.com' via Code Élément (ou Code Domaine)
dm_col = None
for c in ["Code Élément", "Code Domaine"]:
    try:
        _ = pd.read_csv(path, usecols=["Zone", c], nrows=0)
        dm_col = c
        break
    except Exception:
        continue
if dm_col is None:
    raise ValueError("Aucune colonne 'Code Élément' ou 'Code Domaine' trouvée dans le CSV.")

dm_df = pd.read_csv(path, usecols=["Zone", dm_col],
                    dtype={"Zone": "string", dm_col: "string"}, low_memory=True)
allowed_zones = (
    dm_df.loc[dm_df[dm_col].astype(str).str.strip().str.casefold() == "donneesmondiales.com", "Zone"]
         .dropna().unique().tolist()
)
M_country = M_country[M_country["Zone"].isin(allowed_zones)].copy()
if M_country.empty:
    raise ValueError("Aucune donnée après filtre 'donneesmondiales.com'.")

# 4) Mapping Zone -> Region + exclusion "Inconnu" / NaN
reg_df = pd.read_csv(path, usecols=["Zone", "Region"],
                     dtype={"Zone": "string", "Region": "string"}, low_memory=True)
reg_df = reg_df.dropna(subset=["Zone"]).drop_duplicates(subset=["Zone"])
zone_to_region = reg_df.set_index("Zone")["Region"].to_dict()

M_country["Region"] = M_country["Zone"].map(zone_to_region)
mask_inconnu = M_country["Region"].astype(str).str.strip().str.casefold().eq("inconnu")
if mask_inconnu.any():
    print(f"[Info] {int(mask_inconnu.sum())} ligne(s) Region='Inconnu' retirée(s).")
M_country = M_country[~mask_inconnu].dropna(subset=["Region"]).copy()

# 5) Agrégation au niveau RÉGION (médiane des PC + N pays)
M_region = (
    M_country.groupby("Region")
             .agg({**{c: "median" for c in pc_cols}, "Zone": "nunique"})
             .rename(columns={"Zone": "N"})
             .reset_index()
)
n_regions = M_region.shape[0]
if n_regions < 2:
    raise ValueError("Trop peu de régions pour K-means.")

Xk = M_region[pc_cols].to_numpy()

# 6) Sélection de k par silhouette (k ∈ [2, min(10, n_regions-1)]) + inertie (coude)
def fit_kmeans(X, k, random_state=42):
    try:  # sklearn >= 1.4
        return KMeans(n_clusters=k, init='k-means++', n_init='auto', random_state=random_state).fit(X)
    except TypeError:  # compat versions < 1.4
        return KMeans(n_clusters=k, init='k-means++', n_init=10, random_state=random_state).fit(X)

upper_k = max(2, min(10, n_regions - 1))  # silhouette défini si k <= n_samples-1
ks = list(range(2, upper_k + 1)) if n_regions >= 3 else [2]
sil_vals, inertias = [], []

for k in ks:
    km = fit_kmeans(Xk, k)
    inertias.append(km.inertia_)
    # silhouette seulement si k < n_regions (par définition)
    s = silhouette_score(Xk, km.labels_) if (n_regions >= 3 and k <= n_regions - 1) else np.nan
    sil_vals.append(s)

# Choix auto: k avec silhouette max (sinon fallback k=2)
if np.all(np.isnan(sil_vals)):
    k_best = 2 if n_regions >= 2 else 1
else:
    k_best = int(ks[int(np.nanargmax(sil_vals))])

# 7) Entraînement final + sorties
km_final = fit_kmeans(Xk, k_best)
labels = km_final.labels_
centers = km_final.cluster_centers_

out_reg = M_region.copy()
out_reg["Cluster"] = labels + 1  # 1..k
out_reg.to_csv("KMEANS_regions_scoresPCA.csv", index=False)

print(f"\n=== K-means RÉGIONS (PC1..PC{n_keep}) — k choisi = {k_best} ===")
print(f"Variance expliquée cumulée PC1..PC{n_keep} : {cumvar[n_keep-1]*100:.1f}%")
print("\nSilhouette par k :", " | ".join([f"{k}:{s:.3f}" for k, s in zip(ks, sil_vals)]))
sizes = out_reg.value_counts("Cluster").sort_index()
print("\nTaille des clusters (régions) :")
print(sizes.to_string())

# 8) Graphiques : silhouette & inertie (coude)
plt.figure()
plt.plot(ks, sil_vals, marker="o")
plt.xlabel("k (nombre de clusters)")
plt.ylabel("Silhouette moyenne [-1,1]")
plt.title("Sélection de k — Silhouette (K-means, RÉGIONS)")
plt.grid(True, linestyle="--", linewidth=0.5)
plt.tight_layout()
plt.savefig("KMEANS_Regions_Silhouette.png", dpi=150, bbox_inches="tight")
plt.show()

plt.figure()
plt.plot(ks, inertias, marker="o")
plt.xlabel("k (nombre de clusters)")
plt.ylabel("Inertie (WSS)")
plt.title("Sélection de k — Coude (Inertie) — RÉGIONS")
plt.grid(True, linestyle="--", linewidth=0.5)
plt.tight_layout()
plt.savefig("KMEANS_Regions_Coude_Inertie.png", dpi=150, bbox_inches="tight")
plt.show()

# 9) Scatter PC1×PC2 (un point = une RÉGION) coloré par cluster, légende à droite
plt.figure(figsize=(9, 6))
palette = plt.cm.get_cmap("tab10", len(np.unique(labels)))
for c in sorted(out_reg["Cluster"].unique()):
    sub = out_reg[out_reg["Cluster"] == c]
    plt.scatter(sub["PC1"], sub["PC2"], s=80, label=f"Cluster {c}", color=palette(c-1))
    # annotations des régions
    for _, r in sub.iterrows():
        plt.annotate(r["Region"], (r["PC1"], r["PC2"]), fontsize=8)

plt.axhline(0, linewidth=0.5); plt.axvline(0, linewidth=0.5)
plt.xlabel("PC1 (Volume)"); plt.ylabel("PC2 (Intensité)")
plt.title(f"K-means — RÉGIONS — Projection PC1×PC2 (k={k_best})")
plt.legend(title="Cluster", loc="center left", bbox_to_anchor=(1.02, 0.5), frameon=True)
plt.tight_layout()
plt.savefig("KMEANS_Regions_PC1xPC2.png", dpi=150, bbox_inches="tight")
plt.show()

# 10) (Optionnel) Régions les plus proches de leur centre de cluster (dans l'espace PCA)
idxs, dists = pairwise_distances_argmin_min(Xk, centers)
tmp = out_reg.copy()
tmp["_dist_center"] = dists
for c in sorted(tmp["Cluster"].unique()):
    t = tmp[tmp["Cluster"] == c].sort_values("_dist_center").head(10)
    print(f"\n[Cluster {c}] 10 régions les + proches du centre :")
    print(t[["Region", "PC1", "PC2", "N", "_dist_center"]].round(3).to_string(index=False))

# === PARAMÈTRES EFFECTIFS (à coller à la fin du bloc 18) ===
# Silhouette du modèle final (définie seulement si 2 ≤ k ≤ n_regions-1)
if n_regions >= 3 and k_best <= n_regions - 1:
    sil_final = silhouette_score(Xk, labels)
else:
    sil_final = np.nan

print("\n--- PARAMÈTRES EFFECTIFS (K-means RÉGIONS) ---")
print(f"k choisi (silhouette) : {k_best}")
print(f"init: k-means++ | n_init: {km_final.n_init}")
print(f"random_state: 42 | max_iter: {km_final.max_iter} | tol: {km_final.tol}")
print(f"itérations réalisées : {km_final.n_iter_}")
print(f"inertie totale (WSS) : {km_final.inertia_:.3f}")
print(f"Nb de PC utilisées : {n_keep} (≈{cumvar[n_keep-1]*100:.1f}% de variance)")
print(f"Nb de RÉGIONS : {n_regions}")
print("Silhouette finale :", "NA" if np.isnan(sil_final) else f"{sil_final:.3f}")


print("\nFichiers exportés :")
print(" - KMEANS_regions_scoresPCA.csv")
print(" - KMEANS_Regions_PC1xPC2.png")
print(" - KMEANS_Regions_Silhouette.png")
print(" - KMEANS_Regions_Coude_Inertie.png")

# ============================================================
# SORTIES K-MEANS DEMANDÉES :
# - Affectations (pays -> cluster)
# - Centroids par cluster (PC-space + variables d'origine)
# - Caractéristiques communes par cluster (médianes + z-scores)
# A coller après ton bloc K-means (où 'out', 'km_final', 'centers',
# 'k_best', 'n_keep', 'cumvar', 'M' etc. ont été créés).
# Nécessite aussi les objets de l'ACP: 'pca', 'scaler', 'pivot_last',
# et la liste 'colonnes_features' (sinon on la re-déduit).
# ============================================================

import numpy as np
import pandas as pd

# -------------------------------
# 0) Sécurité sur les colonnes
# -------------------------------
if 'colonnes_features' not in globals() or not isinstance(colonnes_features, (list, tuple)):
    # On réinfère les colonnes "métier" depuis pivot_last (hors Zone/Année)
    colonnes_features = [c for c in pivot_last.columns if c not in ["Zone", "Année"]]

# -------------------------------
# 1) Groupe de classe (affectations)
# -------------------------------
assign = out[["Zone", "Année", "Cluster"]].sort_values(["Cluster", "Zone"]).reset_index(drop=True)
assign.to_csv("KMEANS_assignations_pays.csv", index=False)
print("\n=== AFFECTATIONS PAYS → CLUSTER ===")
print(assign.head(20).to_string(index=False))
print("... (voir le CSV complet : KMEANS_assignations_pays.csv)")

# -------------------------------
# 2) Centroids par cluster
#    a) en espace PC (PC1..PCm gardées)
#    b) reprojetés dans l'espace des variables d'origine
# -------------------------------

# a) Centroids en PC-space
centers_pc = pd.DataFrame(
    centers,  # shape = (k, n_keep)
    columns=[f"PC{i+1}" for i in range(n_keep)],
    index=[f"Cluster {i}" for i in range(1, k_best+1)]
).round(4)
centers_pc.to_csv("KMEANS_centroids_PC.csv")
print(f"\n=== CENTROIDS (PC-space, {n_keep} composantes, ≈{cumvar[n_keep-1]*100:.1f}% var.) ===")
print(centers_pc.to_string())

# b) Centroids reprojetés vers les variables d'origine
centers_orig_df = None
try:
    # Inversion PCA -> on revient à l'espace "X_scaled" (standardisé),
    # puis on "dés-standardise" pour retrouver les unités d'origine.
    centers_std = pca.inverse_transform(centers)                # ~ X_scaled reconstruit  :contentReference[oaicite:3]{index=3}
    centers_orig = scaler.inverse_transform(centers_std)         # variables d'origine     :contentReference[oaicite:4]{index=4}
    centers_orig_df = pd.DataFrame(
        centers_orig,
        columns=colonnes_features,
        index=[f"Cluster {i}" for i in range(1, k_best+1)]
    )
    centers_orig_df_rounded = centers_orig_df.round(3)
    centers_orig_df_rounded.to_csv("KMEANS_centroids_variables_origine.csv")
    print("\n=== CENTROIDS (variables d'origine, unités métier) ===")
    # Affiche les 10 premières colonnes pour éviter un pavé énorme
    n_show = min(10, centers_orig_df_rounded.shape[1])
    print(centers_orig_df_rounded.iloc[:, :n_show].to_string())
    if centers_orig_df_rounded.shape[1] > n_show:
        print(f"... ({centers_orig_df_rounded.shape[1]-n_show} colonnes supplémentaires dans le CSV)")
except Exception as e:
    print("\n[Info] Centroids en unités d'origine non calculés :", e)
    print("        (vérifie que 'pca' et 'scaler' existent depuis l'ACP)")

# -------------------------------
# 3) Caractéristiques communes par classe
#    - médianes par cluster (unités d'origine)
#    - z-scores par cluster vs moyenne globale
#    - top variables distinctives (±)
# -------------------------------

# On repart des variables d'origine pour les pays encore en lice (sans Chine, etc.)
meta = pivot_last.merge(assign[["Zone", "Cluster"]], on="Zone", how="inner")
# restreindre aux colonnes effectivement utilisées dans l'ACP (après variance nulle)
features_in_meta = [c for c in colonnes_features if c in meta.columns]

# a) Médianes par cluster
prof_med = meta.groupby("Cluster")[features_in_meta].median().round(3)
prof_med.to_csv("KMEANS_profils_medianes_par_cluster.csv")
print("\n=== PROFILS (médianes par cluster, variables d'origine) ===")
n_show = min(10, prof_med.shape[1])
print(prof_med.iloc[:, :n_show].to_string())
if prof_med.shape[1] > n_show:
    print(f"... ({prof_med.shape[1]-n_show} colonnes supplémentaires dans le CSV)")

# b) z-scores par cluster (moyenne cluster - moyenne globale) / std globale
glob_mean = meta[features_in_meta].mean()
glob_std  = meta[features_in_meta].std(ddof=0).replace(0, np.nan)  # évite divisions par 0
prof_mean = meta.groupby("Cluster")[features_in_meta].mean()

prof_z = ((prof_mean - glob_mean) / glob_std).fillna(0).round(3)
prof_z.to_csv("KMEANS_profils_zscores_par_cluster.csv")

# c) Top variables distinctives par cluster (positives et négatives)
TOP = 5
print(f"\n=== TOP VARS DISTINCTIVES (z-score) par cluster (Top ±{TOP}) ===")
for c in sorted(prof_z.index):
    z = prof_z.loc[c].sort_values(ascending=False)
    top_pos = z.head(TOP)
    top_neg = z.tail(TOP)
    print(f"\n[Cluster {c}]  Variables surreprésentées (z > 0) :")
    for name, val in top_pos.items():
        print(f"  + {name:60s}  z={val:6.3f}")
    print(f"[Cluster {c}]  Variables sous-représentées (z < 0) :")
    for name, val in top_neg.items():
        print(f"  - {name:60s}  z={val:6.3f}")

print("\nFichiers exportés :")
print(" - KMEANS_assignations_pays.csv")
print(" - KMEANS_centroids_PC.csv")
print(" - KMEANS_centroids_variables_origine.csv  (si PCA/scaler dispo)")
print(" - KMEANS_profils_medianes_par_cluster.csv")
print(" - KMEANS_profils_zscores_par_cluster.csv")

# 19) SORTIES K-MEANS — RÉGIONS
# - Affectations (région -> cluster)
# - Centroids par cluster (PC-space) + reprojection en variables d'origine
# - Caractéristiques par cluster (médianes + z-scores) au niveau RÉGION
# Prérequis: out_reg, km_final, centers, k_best, n_keep, cumvar, M_region,
#            pca, scaler, pivot_last, path  (issus de l'ACP + bloc 18).
# Tolérant: si 'allowed_zones' et 'zone_to_region' manquent, on les re-dérive.

import numpy as np
import pandas as pd

# --- Sécurité colonnes "métier" (si non dispo) ---
if 'colonnes_features' not in globals() or not isinstance(colonnes_features, (list, tuple)):
    colonnes_features = [c for c in pivot_last.columns if c not in ["Zone", "Année"]]

# --- 0) (Re)construction des filtres si besoin (donneesmondiales.com + mapping Region) ---
if 'allowed_zones' not in globals():
    dm_col = None
    for c in ["Code Élément", "Code Domaine"]:
        try:
            _ = pd.read_csv(path, usecols=["Zone", c], nrows=0)
            dm_col = c; break
        except Exception:
            continue
    if dm_col is None:
        raise ValueError("Aucune colonne 'Code Élément' ou 'Code Domaine' trouvée.")
    dm_df = pd.read_csv(path, usecols=["Zone", dm_col],
                        dtype={"Zone": "string", dm_col: "string"}, low_memory=True)
    allowed_zones = (
        dm_df.loc[dm_df[dm_col].astype(str).str.strip().str.casefold() == "donneesmondiales.com", "Zone"]
             .dropna().unique().tolist()
    )

if 'zone_to_region' not in globals():
    reg_df = pd.read_csv(path, usecols=["Zone", "Region"],
                         dtype={"Zone": "string", "Region": "string"}, low_memory=True)
    reg_df = reg_df.dropna(subset=["Zone"]).drop_duplicates(subset=["Zone"])
    zone_to_region = reg_df.set_index("Zone")["Region"].to_dict()

# -------------------------------
# 1) Affectations (RÉGION -> CLUSTER)
# -------------------------------
assign_reg = out_reg[["Region", "Cluster"]].copy()
if "N" in out_reg.columns:
    assign_reg["N"] = out_reg["N"]  # nb de pays par région si dispo
assign_reg = assign_reg.sort_values(["Cluster", "Region"]).reset_index(drop=True)
assign_reg.to_csv("KMEANS_assignations_regions.csv", index=False)

print("\n=== AFFECTATIONS RÉGIONS → CLUSTER ===")
print(assign_reg.head(20).to_string(index=False))
print("... (CSV complet : KMEANS_assignations_regions.csv)")

# -------------------------------
# 2) Centroids par cluster
#    a) en PC-space
#    b) reprojetés dans l'espace des variables d'origine
# -------------------------------

# a) Centroids en espace PC (PC1..PCn_keep)
centers_pc = pd.DataFrame(
    centers,  # (k_best, n_keep)
    columns=[f"PC{i+1}" for i in range(n_keep)],
    index=[f"Cluster {i}" for i in range(1, k_best+1)]
).round(4)
centers_pc.to_csv("KMEANS_regions_centroids_PC.csv")
print(f"\n=== CENTROIDS RÉGIONS (PC-space, {n_keep} composantes, ≈{cumvar[n_keep-1]*100:.1f}% var.) ===")
print(centers_pc.to_string())

# b) Reprojection vers variables d'origine
#    -> Reconstruit d'abord dans l'espace "standardisé" (X_scaled) via components_ + mean_,
#       puis dé-standardise via StandardScaler.inverse_transform pour revenir aux unités métier.
centers_orig_df = None
try:
    comps_keep = pca.components_[:n_keep, :]            # (n_keep, n_features)
    mean_scaled = pca.mean_                              # (n_features,)
    centers_std = centers @ comps_keep + mean_scaled     # (k_best, n_features)
    centers_orig = scaler.inverse_transform(centers_std) # (k_best, n_features)
    centers_orig_df = pd.DataFrame(
        centers_orig,
        columns=colonnes_features,
        index=[f"Cluster {i}" for i in range(1, k_best+1)]
    )
    centers_orig_df_rounded = centers_orig_df.round(3)
    centers_orig_df_rounded.to_csv("KMEANS_regions_centroids_variables_origine.csv")
    print("\n=== CENTROIDS RÉGIONS (variables d'origine, unités métier) ===")
    n_show = min(10, centers_orig_df_rounded.shape[1])
    print(centers_orig_df_rounded.iloc[:, :n_show].to_string())
    if centers_orig_df_rounded.shape[1] > n_show:
        print(f"... ({centers_orig_df_rounded.shape[1]-n_show} colonnes supplémentaires dans le CSV)")
except Exception as e:
    print("\n[Info] Centroids (unités d'origine) non calculés :", e)
    print("      (vérifie que 'pca' et 'scaler' existent et que 'colonnes_features' correspond)")

# -------------------------------
# 3) Caractéristiques par cluster (au niveau RÉGION)
#    - médianes par cluster (unités d'origine)
#    - z-scores par cluster vs moyenne globale (entre régions)
#    - Top ± variables distinctives
# -------------------------------

# a) Variables d'origine agrégées au NIVEAU RÉGION (médiane des pays de la région)
meta = pivot_last.copy()
# mêmes filtres que K-means régions (donneesmondiales.com / Chine / Inconnu)
mask_rm = meta["Zone"].astype(str).str.strip().str.casefold().isin(["chine, continentale", "chine"])
meta = meta[~mask_rm].copy()
meta = meta[meta["Zone"].isin(allowed_zones)].copy()
meta["Region"] = meta["Zone"].map(zone_to_region)
mask_inc = meta["Region"].astype(str).str.strip().str.casefold().eq("inconnu")
meta = meta[~mask_inc].dropna(subset=["Region"]).copy()

features_in_meta = [c for c in colonnes_features if c in meta.columns]
meta_reg = meta.groupby("Region")[features_in_meta].median()

# b) Joindre le cluster des régions
clusters_reg = assign_reg.set_index("Region")["Cluster"]
meta_reg_cl = meta_reg.join(clusters_reg, how="inner")
prof_med = meta_reg_cl.groupby("Cluster")[features_in_meta].median().round(3)
prof_med.to_csv("KMEANS_regions_profils_medianes_par_cluster.csv")

print("\n=== PROFILS RÉGIONS (médianes par cluster, variables d'origine) ===")
n_show = min(10, prof_med.shape[1])
print(prof_med.iloc[:, :n_show].to_string())
if prof_med.shape[1] > n_show:
    print(f"... ({prof_med.shape[1]-n_show} colonnes supplémentaires dans le CSV)")

# c) z-scores par cluster (entre régions)
glob_mean = meta_reg[features_in_meta].mean()
glob_std  = meta_reg[features_in_meta].std(ddof=0).replace(0, np.nan)
prof_mean = meta_reg_cl.groupby("Cluster")[features_in_meta].mean()
prof_z = ((prof_mean - glob_mean) / glob_std).fillna(0).round(3)
prof_z.to_csv("KMEANS_regions_profils_zscores_par_cluster.csv")

# d) Top variables distinctives (±)
TOP = 5
print(f"\n=== TOP VARS DISTINCTIVES (z-score) par cluster RÉGIONS (Top ±{TOP}) ===")
for c in sorted(prof_z.index):
    z = prof_z.loc[c].sort_values(ascending=False)
    top_pos = z.head(TOP); top_neg = z.tail(TOP)
    print(f"\n[Cluster {c}]  Variables surreprésentées (z > 0) :")
    for name, val in top_pos.items():
        print(f"  + {name:60s}  z={val:6.3f}")
    print(f"[Cluster {c}]  Variables sous-représentées (z < 0) :")
    for name, val in top_neg.items():
        print(f"  - {name:60s}  z={val:6.3f}")

print("\nFichiers exportés :")
print(" - KMEANS_assignations_regions.csv")
print(" - KMEANS_regions_centroids_PC.csv")
print(" - KMEANS_regions_centroids_variables_origine.csv  (si PCA/scaler dispo)")
print(" - KMEANS_regions_profils_medianes_par_cluster.csv")
print(" - KMEANS_regions_profils_zscores_par_cluster.csv")